page_index,status,error
10,enqueued,
11,enqueued,
12,enqueued,
13,enqueued,
14,enqueued,
15,enqueued,
16,enqueued,
17,enqueued,
18,enqueued,
19,enqueued,
20,enqueued,
21,enqueued,
22,enqueued,
23,enqueued,
24,enqueued,
25,enqueued,
26,enqueued,
27,enqueued,
28,enqueued,
29,enqueued,
30,enqueued,
21,success,
18,success,
16,success,
10,success,
25,success,
26,success,
22,success,
28,success,
30,success,
14,success,
20,success,
12,success,
13,success,
23,success,
29,success,
15,success,
24,success,
11,success,
17,success,
27,success,
19,error,"Traceback (most recent call last):
  File ""/accesssible_digital_textbooks/accessible_digital_textbooks/textbook_processor.py"", line 817, in callback_sectioning
    for inferred_section in inferred_sections:
TypeError: 'NoneType' object is not iterable
"
